services:
  db:
    image: postgres:16
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d

  auth-service:
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - DB_USER
      - DB_PASSWORD
      - DB_NAME
      - DB_HOST=db
      - DB_PORT=5432
      - JWT_SECRET_KEY
    restart: unless-stopped

